package com.github.hzw.security.entity;

import java.util.Date;

import com.github.hzw.util.ExcelDataMapper;

public class ClothPrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_price.id
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_price.cloth_id
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    private Integer clothId;
    private String clothName;
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_price.price
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_price.create_time
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_price.standard
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    private String standard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_price.id
     *
     * @return the value of cloth_price.id
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    @ExcelDataMapper(title="id",order=1)
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_price.id
     *
     * @param id the value for cloth_price.id
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_price.cloth_id
     *
     * @return the value of cloth_price.cloth_id
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    public Integer getClothId() {
        return clothId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_price.cloth_id
     *
     * @param clothId the value for cloth_price.cloth_id
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    public void setClothId(Integer clothId) {
        this.clothId = clothId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_price.price
     *
     * @return the value of cloth_price.price
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_price.price
     *
     * @param price the value for cloth_price.price
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_price.create_time
     *
     * @return the value of cloth_price.create_time
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_price.create_time
     *
     * @param createTime the value for cloth_price.create_time
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_price.standard
     *
     * @return the value of cloth_price.standard
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_price.standard
     *
     * @param standard the value for cloth_price.standard
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    public void setStandard(String standard) {
        this.standard = standard;
    }

	public String getClothName() {
		return clothName;
	}

	public void setClothName(String clothName) {
		this.clothName = clothName;
	}

	@Override
	public String toString() {
		return "ClothPrice [id=" + id + ", clothId=" + clothId + ", clothName="
				+ clothName + ", price=" + price + ", createTime=" + createTime
				+ ", standard=" + standard + "]";
	}
    
    
}