package com.github.hzw.security.entity;

import java.util.Date;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import com.github.hzw.util.ExcelDataMapper;
import com.github.hzw.util.JsonDateSerializer;

public class ClothInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_info.id
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_info.code
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_info.cloth_name
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private String clothName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_info.order_name
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private String orderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_info.create_Time
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_info.mark
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_info.id
     *
     * @return the value of cloth_info.id
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    
    @ExcelDataMapper(title="id",order=1)
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_info.id
     *
     * @param id the value for cloth_info.id
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_info.code
     *
     * @return the value of cloth_info.code
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    @ExcelDataMapper(title="编号",order=2)
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_info.code
     *
     * @param code the value for cloth_info.code
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_info.cloth_name
     *
     * @return the value of cloth_info.cloth_name
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    @ExcelDataMapper(title="布种名称",order=3)
    public String getClothName() {
        return clothName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_info.cloth_name
     *
     * @param clothName the value for cloth_info.cloth_name
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public void setClothName(String clothName) {
        this.clothName = clothName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_info.order_name
     *
     * @return the value of cloth_info.order_name
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    @ExcelDataMapper(title="下单名称",order=4)
    public String getOrderName() {
        return orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_info.order_name
     *
     * @param orderName the value for cloth_info.order_name
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_info.create_Time
     *
     * @return the value of cloth_info.create_Time
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    
    @ExcelDataMapper(title="创建时间",order=5)
	@JsonSerialize(using=JsonDateSerializer.class)
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_info.create_Time
     *
     * @param createTime the value for cloth_info.create_Time
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_info.mark
     *
     * @return the value of cloth_info.mark
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_info.mark
     *
     * @param mark the value for cloth_info.mark
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

	@Override
	public String toString() {
		return "ClothInfo [id=" + id + ", code=" + code + ", clothName="
				+ clothName + ", orderName=" + orderName + ", createTime="
				+ createTime + ", mark=" + mark + "]";
	}
    
    
    
}