package com.github.hzw.security.entity;

import java.util.Date;

import com.github.hzw.util.ExcelDataMapper;

public class ClothPrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_price.id
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_price.cloth_id
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    private Integer clothId;
    private String clothName;
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_price.price
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_price.create_time
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_price.standard
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    // private String standard;
    private int kuanfu;
    private int kuanfufs; // '宽幅方式 0包边  1实用' ,
    private String kuanfufsStr;
    private int kezhong;
    private int kezhongUnit; // '克重单位 0 G/M2 1 G/Y 2 G/M' ,
    private String kezhongUnitStr;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_price.id
     *
     * @return the value of cloth_price.id
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    @ExcelDataMapper(title="id",order=1)
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_price.id
     *
     * @param id the value for cloth_price.id
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_price.cloth_id
     *
     * @return the value of cloth_price.cloth_id
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    public Integer getClothId() {
        return clothId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_price.cloth_id
     *
     * @param clothId the value for cloth_price.cloth_id
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    public void setClothId(Integer clothId) {
        this.clothId = clothId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_price.price
     *
     * @return the value of cloth_price.price
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_price.price
     *
     * @param price the value for cloth_price.price
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_price.create_time
     *
     * @return the value of cloth_price.create_time
     *
     * @mbggenerated Sun Mar 22 11:36:09 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

   
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

   

	public String getClothName() {
		return clothName;
	}

	public void setClothName(String clothName) {
		this.clothName = clothName;
	}

	public int getKuanfu() {
		return kuanfu;
	}

	public void setKuanfu(int kuanfu) {
		this.kuanfu = kuanfu;
	}

	
	public int getKuanfufs() {
		return kuanfufs;
	}

	// '宽幅方式 0包边  1实用' ,
	public void setKuanfufs(int kuanfufs) {
		this.kuanfufs = kuanfufs;
		if(kuanfufs == 1) {
			kuanfufsStr = "实用";
		} else {
			kuanfufsStr = "包边";
		}
	}

	public int getKezhong() {
		return kezhong;
	}

	public void setKezhong(int kezhong) {
		this.kezhong = kezhong;
	}

	public int getKezhongUnit() {
		return kezhongUnit;
	}

	// '克重单位 0 G/M2 1 G/Y 2 G/M' 
	public void setKezhongUnit(int kezhongUnit) {
		this.kezhongUnit = kezhongUnit;
		if(kezhongUnit == 1) {
			kezhongUnitStr = "G/Y";
		} else if(kezhongUnit == 2) {
			kezhongUnitStr = "G/M";
		} else {
			kezhongUnitStr = "G/M2";
		}
	}

	@Override
	public String toString() {
		return "ClothPrice [id=" + id + ", clothId=" + clothId + ", clothName="
				+ clothName + ", price=" + price + ", createTime=" + createTime
				+ ", kuanfu=" + kuanfu + ", kuanfufs=" + kuanfufs
				+ ", kezhong=" + kezhong + ", kezhongUnit=" + kezhongUnit + "]";
	}

	public String getKuanfufsStr() {
		return kuanfufsStr;
	}

	public void setKuanfufsStr(String kuanfufsStr) {
		this.kuanfufsStr = kuanfufsStr;
	}

	public String getKezhongUnitStr() {
		return kezhongUnitStr;
	}

	public void setKezhongUnitStr(String kezhongUnitStr) {
		this.kezhongUnitStr = kezhongUnitStr;
	}

    
    
}