package com.github.hzw.security.entity;

import java.util.Date;

import com.github.hzw.util.ExcelDataMapper;

public class ClothAllowance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_allowance.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_allowance.cloth_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer clothId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_allowance.factory_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer factoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_allowance.allowance
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer allowance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_allowance.unit
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_allowance.old_sum
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer oldSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_allowance.change_sum
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer changeSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_allowance.create_time
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_allowance.mark
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_allowance.id
     *
     * @return the value of cloth_allowance.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    
    @ExcelDataMapper(title="id",order=1)
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_allowance.id
     *
     * @param id the value for cloth_allowance.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_allowance.cloth_id
     *
     * @return the value of cloth_allowance.cloth_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="布种",order=2)
    public Integer getClothId() {
        return clothId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_allowance.cloth_id
     *
     * @param clothId the value for cloth_allowance.cloth_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setClothId(Integer clothId) {
        this.clothId = clothId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_allowance.factory_id
     *
     * @return the value of cloth_allowance.factory_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    
    @ExcelDataMapper(title="工厂",order=2)
    public Integer getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_allowance.factory_id
     *
     * @param factoryId the value for cloth_allowance.factory_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setFactoryId(Integer factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_allowance.allowance
     *
     * @return the value of cloth_allowance.allowance
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="余量",order=3)
    public Integer getAllowance() {
        return allowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_allowance.allowance
     *
     * @param allowance the value for cloth_allowance.allowance
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setAllowance(Integer allowance) {
        this.allowance = allowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_allowance.unit
     *
     * @return the value of cloth_allowance.unit
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="单位",order=4)
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_allowance.unit
     *
     * @param unit the value for cloth_allowance.unit
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_allowance.old_sum
     *
     * @return the value of cloth_allowance.old_sum
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="前余量",order=5)
    public Integer getOldSum() {
        return oldSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_allowance.old_sum
     *
     * @param oldSum the value for cloth_allowance.old_sum
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setOldSum(Integer oldSum) {
        this.oldSum = oldSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_allowance.change_sum
     *
     * @return the value of cloth_allowance.change_sum
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="改变量",order=6)
    public Integer getChangeSum() {
        return changeSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_allowance.change_sum
     *
     * @param changeSum the value for cloth_allowance.change_sum
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setChangeSum(Integer changeSum) {
        this.changeSum = changeSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_allowance.create_time
     *
     * @return the value of cloth_allowance.create_time
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_allowance.create_time
     *
     * @param createTime the value for cloth_allowance.create_time
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_allowance.mark
     *
     * @return the value of cloth_allowance.mark
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="备注",order=7)
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_allowance.mark
     *
     * @param mark the value for cloth_allowance.mark
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setMark(String mark) {
        this.mark = mark;
    }
}