package com.github.hzw.security.entity;

import java.util.Date;

import com.github.hzw.util.DateUtil;
import com.github.hzw.util.ExcelDataMapper;

public class ClothAllowance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_allowance.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer id;

    private Integer clothId;

    private String clothName; // 冗余
    
    private Integer factoryId;
    
    // 工厂名称
    private String factoryName; // 冗余
    private Double allowance;
    private int unit; // 布种单位   0条 1 kg 2cm 3码
    private Double oldSum;
    private Double changeSum;
    private Double allowancekg;
    private int unitkg; // 布种单位   0条 1 kg 2cm 3码
    private Double oldSumkg;
    private Double changeSumkg;
    
    private Date createTime;

    private String mark;

    private Date inputDate;
    
    private String strInputDate;
    
    @ExcelDataMapper(title="id",order=1)
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ExcelDataMapper(title="布种",order=2)
    public Integer getClothId() {
        return clothId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_allowance.cloth_id
     *
     * @param clothId the value for cloth_allowance.cloth_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setClothId(Integer clothId) {
        this.clothId = clothId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_allowance.factory_id
     *
     * @return the value of cloth_allowance.factory_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    
    @ExcelDataMapper(title="工厂",order=2)
    public Integer getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_allowance.factory_id
     *
     * @param factoryId the value for cloth_allowance.factory_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setFactoryId(Integer factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_allowance.allowance
     *
     * @return the value of cloth_allowance.allowance
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="余量",order=3)
    public Double getAllowance() {
        return allowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_allowance.allowance
     *
     * @param allowance the value for cloth_allowance.allowance
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setAllowance(Double allowance) {
        this.allowance = allowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_allowance.unit
     *
     * @return the value of cloth_allowance.unit
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="单位",order=4)
    public Integer getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_allowance.unit
     *
     * @param unit the value for cloth_allowance.unit
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setUnit(Integer unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_allowance.old_sum
     *
     * @return the value of cloth_allowance.old_sum
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="前余量",order=5)
    public Double getOldSum() {
        return oldSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_allowance.old_sum
     *
     * @param oldSum the value for cloth_allowance.old_sum
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setOldSum(Double oldSum) {
        this.oldSum = oldSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_allowance.change_sum
     *
     * @return the value of cloth_allowance.change_sum
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="改变量",order=6)
    public Double getChangeSum() {
        return changeSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_allowance.change_sum
     *
     * @param changeSum the value for cloth_allowance.change_sum
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setChangeSum(Double changeSum) {
        this.changeSum = changeSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_allowance.create_time
     *
     * @return the value of cloth_allowance.create_time
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_allowance.create_time
     *
     * @param createTime the value for cloth_allowance.create_time
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_allowance.mark
     *
     * @return the value of cloth_allowance.mark
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="备注",order=7)
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_allowance.mark
     *
     * @param mark the value for cloth_allowance.mark
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

	public String getFactoryName() {
		return factoryName;
	}

	public void setFactoryName(String factoryName) {
		this.factoryName = factoryName;
	}


	public String getClothName() {
		return clothName;
	}

	public void setClothName(String clothName) {
		this.clothName = clothName;
	}

	public Date getInputDate() {
		return inputDate;
	}

	public void setInputDate(Date inputDate) {
		this.strInputDate = DateUtil.date2Str(inputDate, "yyyy-MM-dd");
		this.inputDate = inputDate;
	}

	public String getStrInputDate() {
		return strInputDate;
	}

	public void setStrInputDate(String strInputDate) {
		this.strInputDate = strInputDate;
	}

	public Double getAllowancekg() {
		return allowancekg;
	}

	public void setAllowancekg(Double allowancekg) {
		this.allowancekg = allowancekg;
	}

	public int getUnitkg() {
		return unitkg;
	}

	public void setUnitkg(int unitkg) {
		this.unitkg = unitkg;
	}

	public Double getOldSumkg() {
		return oldSumkg;
	}

	public void setOldSumkg(Double oldSumkg) {
		this.oldSumkg = oldSumkg;
	}

	public Double getChangeSumkg() {
		return changeSumkg;
	}

	public void setChangeSumkg(Double changeSumkg) {
		this.changeSumkg = changeSumkg;
	}

	public void setUnit(int unit) {
		this.unit = unit;
	}
	
	

}