package com.github.hzw.security.entity;

import com.github.hzw.util.ExcelDataMapper;

public class ClothUnit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_unit.id
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private Integer id;

    private Integer clothId;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_unit.kg
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private Integer kg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_unit.cm
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private Integer cm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_unit.yard
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private Integer yard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_unit.id
     *
     * @return the value of cloth_unit.id
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    @ExcelDataMapper(title="id",order=1)
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_unit.id
     *
     * @param id the value for cloth_unit.id
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_unit.kg
     *
     * @return the value of cloth_unit.kg
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    @ExcelDataMapper(title="公斤",order=3)
    public Integer getKg() {
        return kg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_unit.kg
     *
     * @param kg the value for cloth_unit.kg
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public void setKg(Integer kg) {
        this.kg = kg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_unit.cm
     *
     * @return the value of cloth_unit.cm
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    @ExcelDataMapper(title="米",order=4)
    public Integer getCm() {
        return cm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_unit.cm
     *
     * @param cm the value for cloth_unit.cm
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public void setCm(Integer cm) {
        this.cm = cm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth_unit.yard
     *
     * @return the value of cloth_unit.yard
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    @ExcelDataMapper(title="码",order=5)
    public Integer getYard() {
        return yard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth_unit.yard
     *
     * @param yard the value for cloth_unit.yard
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public void setYard(Integer yard) {
        this.yard = yard;
    }

    @ExcelDataMapper(title="布种",order=2)
	public Integer getClothId() {
		return clothId;
	}

	public void setClothId(Integer clothId) {
		this.clothId = clothId;
	}

	@Override
	public String toString() {
		return "ClothUnit [id=" + id + ", clothId=" + clothId + ", kg=" + kg
				+ ", cm=" + cm + ", yard=" + yard + "]";
	}

	
    
    
}