package com.github.hzw.security.entity;

import java.util.Date;

import com.github.hzw.util.DateUtil;
import com.github.hzw.util.ExcelDataMapper;

public class ClothAllowance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth_allowance.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer id;

    private Integer clothId;

    private String clothName; // 冗余
    
    private Integer factoryId;
    
    // 工厂名称
    private String factoryName; // 冗余
    private Integer allowance;
    private int unit; // 布种单位   0条 1 kg 2cm 3码
    private Double oldSum;
    private Double changeSum;
    private Double allowancekg;
    private int unitkg; // 布种单位   0条 1 kg 2cm 3码
    private Double oldSumkg;
    private Double changeSumkg;
    /***未回数量**/
    private Integer noReturn;
    private Date createTime;
    /***现余量信息**/
    private String allowanceInfo;
    /***现余量信息KG**/
    private String allowanceKgInfo;

    private String mark;

    private Date inputDate;
    
    private String strInputDate;
    
    @ExcelDataMapper(title="id",order=1)
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    
    public Integer getClothId() {
        return clothId;
    }

    
    public void setClothId(Integer clothId) {
        this.clothId = clothId;
    }

    public Integer getFactoryId() {
        return factoryId;
    }

    public void setFactoryId(Integer factoryId) {
        this.factoryId = factoryId;
    }

    
    @ExcelDataMapper(title="余量",order=5)
    public Integer getAllowance() {
        return allowance;
    }

    
    public void setAllowance(Integer allowance) {
        this.allowance = allowance;
    }

    
    @ExcelDataMapper(title="单位",order=4)
    public Integer getUnit() {
        return unit;
    }

    
    public void setUnit(Integer unit) {
        this.unit = unit;
    }

    
    @ExcelDataMapper(title="前余量",order=5)
    public Double getOldSum() {
        return oldSum;
    }

    
    public void setOldSum(Double oldSum) {
        this.oldSum = oldSum;
    }

    
    @ExcelDataMapper(title="新增量",order=6)
    public Double getChangeSum() {
        return changeSum;
    }

    
    public void setChangeSum(Double changeSum) {
        this.changeSum = changeSum;
    }

    
    public Date getCreateTime() {
        return createTime;
    }

    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @ExcelDataMapper(title="备注",order=7)
    public String getMark() {
        return mark;
    }

    
    public void setMark(String mark) {
        this.mark = mark;
    }

    @ExcelDataMapper(title="工厂",order=4)
	public String getFactoryName() {
		return factoryName;
	}

	public void setFactoryName(String factoryName) {
		this.factoryName = factoryName;
	}

	@ExcelDataMapper(title="布种",order=3)
	public String getClothName() {
		return clothName;
	}

	public void setClothName(String clothName) {
		this.clothName = clothName;
	}

	public Date getInputDate() {
		return inputDate;
	}

	public void setInputDate(Date inputDate) {
		this.strInputDate = DateUtil.date2Str(inputDate, "yyyy-MM-dd");
		this.inputDate = inputDate;
	}

	@ExcelDataMapper(title="日期",order=2)
	public String getStrInputDate() {
		return strInputDate;
	}

	public void setStrInputDate(String strInputDate) {
		this.strInputDate = strInputDate;
	}

	public Double getAllowancekg() {
		return allowancekg;
	}

	public void setAllowancekg(Double allowancekg) {
		this.allowancekg = allowancekg;
	}

	public int getUnitkg() {
		return unitkg;
	}

	public void setUnitkg(int unitkg) {
		this.unitkg = unitkg;
	}

	public Double getOldSumkg() {
		return oldSumkg;
	}

	public void setOldSumkg(Double oldSumkg) {
		this.oldSumkg = oldSumkg;
	}

	public Double getChangeSumkg() {
		return changeSumkg;
	}

	public void setChangeSumkg(Double changeSumkg) {
		this.changeSumkg = changeSumkg;
	}

	public void setUnit(int unit) {
		this.unit = unit;
	}
	/***未回数量**/
	public Integer getNoReturn() {
		return noReturn;
	}
	/***未回数量**/
	public void setNoReturn(Integer noReturn) {
		this.noReturn = noReturn;
	}
	/***现余量信息**/
	public String getAllowanceInfo() {
		String unitName="条";
		if(0!=unit){
			unitName="包";
		}
		allowanceInfo=allowance+unitName;
		if(null!=noReturn&&0<noReturn&&unit==0){
			allowanceInfo=(allowance)+unitName+"(未回"+noReturn+unitName+")";
		}
		return allowanceInfo;
	}
	/***现余量信息**/
	public void setAllowanceInfo(String allowanceInfo) {
		this.allowanceInfo = allowanceInfo;
	}
	/***现余量信息KG**/
	public String getAllowanceKgInfo() {
		String unitName="KG";
		allowanceKgInfo=allowancekg+unitName;
		if(null!=noReturn&&0<noReturn&&unit==4){
			allowanceKgInfo=(allowancekg)+unitName+"(未回"+noReturn+unitName+")";
		}
		return allowanceKgInfo;
	}
	/***现余量信息KG**/
	public void setAllowanceKgInfo(String allowanceKgInfo) {
		this.allowanceKgInfo = allowanceKgInfo;
	}

}