package com.github.hzw.security.entity;

public class DateVersion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column date_version.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column date_version.date_k
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String dateK;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column date_version.value_v
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer valueV;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column date_version.id
     *
     * @return the value of date_version.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column date_version.id
     *
     * @param id the value for date_version.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column date_version.date_k
     *
     * @return the value of date_version.date_k
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getDateK() {
        return dateK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column date_version.date_k
     *
     * @param dateK the value for date_version.date_k
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setDateK(String dateK) {
        this.dateK = dateK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column date_version.value_v
     *
     * @return the value of date_version.value_v
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getValueV() {
        return valueV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column date_version.value_v
     *
     * @param valueV the value for date_version.value_v
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setValueV(Integer valueV) {
        this.valueV = valueV;
    }
}