package com.github.hzw.security.entity;

import com.github.hzw.util.ExcelDataMapper;

public class FactoryInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_info.id
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_info.name
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_info.code
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_info.code2
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private String code2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory_info.mark
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_info.id
     *
     * @return the value of factory_info.id
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    @ExcelDataMapper(title="id",order=1)
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_info.id
     *
     * @param id the value for factory_info.id
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_info.name
     *
     * @return the value of factory_info.name
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    @ExcelDataMapper(title="工厂名称",order=2)
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_info.name
     *
     * @param name the value for factory_info.name
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_info.code
     *
     * @return the value of factory_info.code
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    @ExcelDataMapper(title="工厂编号",order=3)
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_info.code
     *
     * @param code the value for factory_info.code
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_info.code2
     *
     * @return the value of factory_info.code2
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    @ExcelDataMapper(title="工厂编号2",order=4)
    public String getCode2() {
        return code2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_info.code2
     *
     * @param code2 the value for factory_info.code2
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public void setCode2(String code2) {
        this.code2 = code2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory_info.mark
     *
     * @return the value of factory_info.mark
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    @ExcelDataMapper(title="备注",order=5)
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory_info.mark
     *
     * @param mark the value for factory_info.mark
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public void setMark(String mark) {
        this.mark = mark;
    }
}