package com.github.hzw.security.entity;

public class FlowerAdditional {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_additional.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_additional.flower_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer flowerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_additional.factory_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String factoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_additional.factory_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String factoryColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_additional.my_company_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String myCompanyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_additional.my_company_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String myCompanyColor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_additional.id
     *
     * @return the value of flower_additional.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_additional.id
     *
     * @param id the value for flower_additional.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_additional.flower_id
     *
     * @return the value of flower_additional.flower_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getFlowerId() {
        return flowerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_additional.flower_id
     *
     * @param flowerId the value for flower_additional.flower_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setFlowerId(Integer flowerId) {
        this.flowerId = flowerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_additional.factory_code
     *
     * @return the value of flower_additional.factory_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getFactoryCode() {
        return factoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_additional.factory_code
     *
     * @param factoryCode the value for flower_additional.factory_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setFactoryCode(String factoryCode) {
        this.factoryCode = factoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_additional.factory_color
     *
     * @return the value of flower_additional.factory_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getFactoryColor() {
        return factoryColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_additional.factory_color
     *
     * @param factoryColor the value for flower_additional.factory_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setFactoryColor(String factoryColor) {
        this.factoryColor = factoryColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_additional.my_company_code
     *
     * @return the value of flower_additional.my_company_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getMyCompanyCode() {
        return myCompanyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_additional.my_company_code
     *
     * @param myCompanyCode the value for flower_additional.my_company_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setMyCompanyCode(String myCompanyCode) {
        this.myCompanyCode = myCompanyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_additional.my_company_color
     *
     * @return the value of flower_additional.my_company_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getMyCompanyColor() {
        return myCompanyColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_additional.my_company_color
     *
     * @param myCompanyColor the value for flower_additional.my_company_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setMyCompanyColor(String myCompanyColor) {
        this.myCompanyColor = myCompanyColor;
    }

	@Override
	public String toString() {
		return "FlowerAdditional [id=" + id + ", flowerId=" + flowerId
				+ ", factoryCode=" + factoryCode + ", factoryColor="
				+ factoryColor + ", myCompanyCode=" + myCompanyCode
				+ ", myCompanyColor=" + myCompanyColor + "]";
	}
    
    
}