package com.github.hzw.security.entity;

import java.util.ArrayList;
import java.util.List;

import com.github.hzw.util.ExcelDataMapper;

public class FlowerInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_info.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer id;

    private Integer factoryId;
    
    private String factoryName;// 冗余
    
    private String myCompanyCode;

    private Integer clothId;
    private String clothName; // 冗余

    // 工厂编号
    private String factoryCode;
    
    private List<FlowerAdditional> list = new ArrayList<FlowerAdditional>();
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_info.file_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String fileColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_info.technology_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer technologyId;
    
    private String technologyName; // 冗余
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_info.picture
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flower_info.status
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_info.id
     *
     * @return the value of flower_info.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="id",order=1)
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_info.id
     *
     * @param id the value for flower_info.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_info.factory_id
     *
     * @return the value of flower_info.factory_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="工厂",order=2)
    public Integer getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_info.factory_id
     *
     * @param factoryId the value for flower_info.factory_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setFactoryId(Integer factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_info.my_company_code
     *
     * @return the value of flower_info.my_company_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="我司编号",order=3)
    public String getMyCompanyCode() {
        return myCompanyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_info.my_company_code
     *
     * @param myCompanyCode the value for flower_info.my_company_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setMyCompanyCode(String myCompanyCode) {
        this.myCompanyCode = myCompanyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_info.cloth_id
     *
     * @return the value of flower_info.cloth_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="布种",order=4)
    public Integer getClothId() {
        return clothId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_info.cloth_id
     *
     * @param clothId the value for flower_info.cloth_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setClothId(Integer clothId) {
        this.clothId = clothId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_info.file_color
     *
     * @return the value of flower_info.file_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="文件分色号",order=5)
    public String getFileColor() {
        return fileColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_info.file_color
     *
     * @param fileColor the value for flower_info.file_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setFileColor(String fileColor) {
        this.fileColor = fileColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_info.technology_id
     *
     * @return the value of flower_info.technology_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="工艺",order=6)
    public Integer getTechnologyId() {
        return technologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_info.technology_id
     *
     * @param technologyId the value for flower_info.technology_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setTechnologyId(Integer technologyId) {
        this.technologyId = technologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_info.picture
     *
     * @return the value of flower_info.picture
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_info.picture
     *
     * @param picture the value for flower_info.picture
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flower_info.status
     *
     * @return the value of flower_info.status
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flower_info.status
     *
     * @param status the value for flower_info.status
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public String getFactoryName() {
		return factoryName;
	}

	public void setFactoryName(String factoryName) {
		this.factoryName = factoryName;
	}

	public String getClothName() {
		return clothName;
	}

	public void setClothName(String clothName) {
		this.clothName = clothName;
	}

	public String getTechnologyName() {
		return technologyName;
	}

	public void setTechnologyName(String technologyName) {
		this.technologyName = technologyName;
	}

	public List<FlowerAdditional> getList() {
		return list;
	}

	public void setList(List<FlowerAdditional> list) {
		this.list = list;
	}

	public String getFactoryCode() {
		return factoryCode;
	}

	public void setFactoryCode(String factoryCode) {
		this.factoryCode = factoryCode;
	}

	@Override
	public String toString() {
		return "FlowerInfo [id=" + id + ", factoryId=" + factoryId
				+ ", factoryName=" + factoryName + ", myCompanyCode="
				+ myCompanyCode + ", clothId=" + clothId + ", clothName="
				+ clothName + ", factoryCode=" + factoryCode + ", list=" + list
				+ ", fileColor=" + fileColor + ", technologyId=" + technologyId
				+ ", technologyName=" + technologyName + ", picture=" + picture
				+ ", status=" + status + "]";
	}

}