package com.github.hzw.security.entity;

import java.util.Date;

import com.github.hzw.util.ExcelDataMapper;

public class Notebook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notebook.id
     *
     * @mbggenerated Thu Mar 19 23:41:57 CST 2015
     */
	
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notebook.userid
     *
     * @mbggenerated Thu Mar 19 23:41:57 CST 2015
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notebook.time
     *
     * @mbggenerated Thu Mar 19 23:41:57 CST 2015
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notebook.title
     *
     * @mbggenerated Thu Mar 19 23:41:57 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notebook.create_time
     *
     * @mbggenerated Thu Mar 19 23:41:57 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notebook.content
     *
     * @mbggenerated Thu Mar 19 23:41:57 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notebook.id
     *
     * @return the value of notebook.id
     *
     * @mbggenerated Thu Mar 19 23:41:57 CST 2015
     */
    @ExcelDataMapper(title="id",order=1)
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notebook.id
     *
     * @param id the value for notebook.id
     *
     * @mbggenerated Thu Mar 19 23:41:57 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notebook.userid
     *
     * @return the value of notebook.userid
     *
     * @mbggenerated Thu Mar 19 23:41:57 CST 2015
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notebook.userid
     *
     * @param userid the value for notebook.userid
     *
     * @mbggenerated Thu Mar 19 23:41:57 CST 2015
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notebook.time
     *
     * @return the value of notebook.time
     *
     * @mbggenerated Thu Mar 19 23:41:57 CST 2015
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notebook.time
     *
     * @param time the value for notebook.time
     *
     * @mbggenerated Thu Mar 19 23:41:57 CST 2015
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notebook.title
     *
     * @return the value of notebook.title
     *
     * @mbggenerated Thu Mar 19 23:41:57 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notebook.title
     *
     * @param title the value for notebook.title
     *
     * @mbggenerated Thu Mar 19 23:41:57 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notebook.create_time
     *
     * @return the value of notebook.create_time
     *
     * @mbggenerated Thu Mar 19 23:41:57 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notebook.create_time
     *
     * @param createTime the value for notebook.create_time
     *
     * @mbggenerated Thu Mar 19 23:41:57 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notebook.content
     *
     * @return the value of notebook.content
     *
     * @mbggenerated Thu Mar 19 23:41:57 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notebook.content
     *
     * @param content the value for notebook.content
     *
     * @mbggenerated Thu Mar 19 23:41:57 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

	@Override
	public String toString() {
		return "Notebook [id=" + id + ", userid=" + userid + ", time=" + time
				+ ", title=" + title + ", createTime=" + createTime
				+ ", content=" + content + "]";
	}
    
    
}