package com.github.hzw.security.entity;

public class OrderSummaryWithBLOBs extends OrderSummary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.salesmans
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String salesmans;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.mark
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.salesmans
     *
     * @return the value of order_summary.salesmans
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getSalesmans() {
        return salesmans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.salesmans
     *
     * @param salesmans the value for order_summary.salesmans
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setSalesmans(String salesmans) {
        this.salesmans = salesmans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.mark
     *
     * @return the value of order_summary.mark
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.mark
     *
     * @param mark the value for order_summary.mark
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setMark(String mark) {
        this.mark = mark;
    }
}