package com.github.hzw.security.entity;

import java.util.Date;

import com.github.hzw.util.ExcelDataMapper;

// 下单录入  关键字  ordersummary
public class OrderSummary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.order_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.order_date
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.cloth_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer clothId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.factory_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer factoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.technology_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer technologyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.my_company_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String myCompanyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.my_company_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String myCompanyColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.factory_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String factoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.factory_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String factoryColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.cloth_num
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer clothNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.num
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.standard
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String standard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.packing_style
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String packingStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.print_status
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer printStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.print_num
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer printNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.status
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.return_status
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer returnStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_summary.createTime
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.id
     *
     * @return the value of order_summary.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="id",order=1)
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.id
     *
     * @param id the value for order_summary.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.order_code
     *
     * @return the value of order_summary.order_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.order_code
     *
     * @param orderCode the value for order_summary.order_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.order_date
     *
     * @return the value of order_summary.order_date
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.order_date
     *
     * @param orderDate the value for order_summary.order_date
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.cloth_id
     *
     * @return the value of order_summary.cloth_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getClothId() {
        return clothId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.cloth_id
     *
     * @param clothId the value for order_summary.cloth_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setClothId(Integer clothId) {
        this.clothId = clothId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.factory_id
     *
     * @return the value of order_summary.factory_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getFactoryId() {
        return factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.factory_id
     *
     * @param factoryId the value for order_summary.factory_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setFactoryId(Integer factoryId) {
        this.factoryId = factoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.technology_id
     *
     * @return the value of order_summary.technology_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getTechnologyId() {
        return technologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.technology_id
     *
     * @param technologyId the value for order_summary.technology_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setTechnologyId(Integer technologyId) {
        this.technologyId = technologyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.my_company_code
     *
     * @return the value of order_summary.my_company_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getMyCompanyCode() {
        return myCompanyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.my_company_code
     *
     * @param myCompanyCode the value for order_summary.my_company_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setMyCompanyCode(String myCompanyCode) {
        this.myCompanyCode = myCompanyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.my_company_color
     *
     * @return the value of order_summary.my_company_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getMyCompanyColor() {
        return myCompanyColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.my_company_color
     *
     * @param myCompanyColor the value for order_summary.my_company_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setMyCompanyColor(String myCompanyColor) {
        this.myCompanyColor = myCompanyColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.factory_code
     *
     * @return the value of order_summary.factory_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getFactoryCode() {
        return factoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.factory_code
     *
     * @param factoryCode the value for order_summary.factory_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setFactoryCode(String factoryCode) {
        this.factoryCode = factoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.factory_color
     *
     * @return the value of order_summary.factory_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getFactoryColor() {
        return factoryColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.factory_color
     *
     * @param factoryColor the value for order_summary.factory_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setFactoryColor(String factoryColor) {
        this.factoryColor = factoryColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.cloth_num
     *
     * @return the value of order_summary.cloth_num
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getClothNum() {
        return clothNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.cloth_num
     *
     * @param clothNum the value for order_summary.cloth_num
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setClothNum(Integer clothNum) {
        this.clothNum = clothNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.num
     *
     * @return the value of order_summary.num
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.num
     *
     * @param num the value for order_summary.num
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.standard
     *
     * @return the value of order_summary.standard
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.standard
     *
     * @param standard the value for order_summary.standard
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setStandard(String standard) {
        this.standard = standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.packing_style
     *
     * @return the value of order_summary.packing_style
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getPackingStyle() {
        return packingStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.packing_style
     *
     * @param packingStyle the value for order_summary.packing_style
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setPackingStyle(String packingStyle) {
        this.packingStyle = packingStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.print_status
     *
     * @return the value of order_summary.print_status
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getPrintStatus() {
        return printStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.print_status
     *
     * @param printStatus the value for order_summary.print_status
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setPrintStatus(Integer printStatus) {
        this.printStatus = printStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.print_num
     *
     * @return the value of order_summary.print_num
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getPrintNum() {
        return printNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.print_num
     *
     * @param printNum the value for order_summary.print_num
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setPrintNum(Integer printNum) {
        this.printNum = printNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.status
     *
     * @return the value of order_summary.status
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.status
     *
     * @param status the value for order_summary.status
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.return_status
     *
     * @return the value of order_summary.return_status
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.return_status
     *
     * @param returnStatus the value for order_summary.return_status
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setReturnStatus(Integer returnStatus) {
        this.returnStatus = returnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_summary.createTime
     *
     * @return the value of order_summary.createTime
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_summary.createTime
     *
     * @param createtime the value for order_summary.createTime
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    
    private String salesmans;

    private String mark;

	public String getSalesmans() {
		return salesmans;
	}

	public void setSalesmans(String salesmans) {
		this.salesmans = salesmans;
	}

	public String getMark() {
		return mark;
	}

	public void setMark(String mark) {
		this.mark = mark;
	}

	@Override
	public String toString() {
		return "OrderSummary [id=" + id + ", orderCode=" + orderCode
				+ ", orderDate=" + orderDate + ", clothId=" + clothId
				+ ", factoryId=" + factoryId + ", technologyId=" + technologyId
				+ ", myCompanyCode=" + myCompanyCode + ", myCompanyColor="
				+ myCompanyColor + ", factoryCode=" + factoryCode
				+ ", factoryColor=" + factoryColor + ", clothNum=" + clothNum
				+ ", num=" + num + ", standard=" + standard + ", packingStyle="
				+ packingStyle + ", printStatus=" + printStatus + ", printNum="
				+ printNum + ", status=" + status + ", returnStatus="
				+ returnStatus + ", createtime=" + createtime + ", salesmans="
				+ salesmans + ", mark=" + mark + "]";
	}
    
    
}