package com.github.hzw.security.entity;

import java.util.Date;

import com.github.hzw.util.ExcelDataMapper;

public class OrderNotifyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_notify_info.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_notify_info.no
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String no;
    
    private int factoryId;
    
    private String factoryName;  // 冗余

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_notify_info.summary_ids
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String summaryIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_notify_info.create_time
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_notify_info.mark
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_notify_info.id
     *
     * @return the value of order_notify_info.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    @ExcelDataMapper(title="id",order=1)
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_notify_info.id
     *
     * @param id the value for order_notify_info.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_notify_info.no
     *
     * @return the value of order_notify_info.no
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_notify_info.no
     *
     * @param no the value for order_notify_info.no
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_notify_info.summary_ids
     *
     * @return the value of order_notify_info.summary_ids
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getSummaryIds() {
        return summaryIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_notify_info.summary_ids
     *
     * @param summaryIds the value for order_notify_info.summary_ids
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setSummaryIds(String summaryIds) {
        this.summaryIds = summaryIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_notify_info.create_time
     *
     * @return the value of order_notify_info.create_time
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_notify_info.create_time
     *
     * @param createTime the value for order_notify_info.create_time
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_notify_info.mark
     *
     * @return the value of order_notify_info.mark
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_notify_info.mark
     *
     * @param mark the value for order_notify_info.mark
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

	public int getFactoryId() {
		return factoryId;
	}

	public void setFactoryId(int factoryId) {
		this.factoryId = factoryId;
	}

	public String getFactoryName() {
		return factoryName;
	}

	public void setFactoryName(String factoryName) {
		this.factoryName = factoryName;
	}

	@Override
	public String toString() {
		return "OrderNotifyInfo [id=" + id + ", no=" + no + ", factoryId="
				+ factoryId + ", factoryName=" + factoryName + ", summaryIds="
				+ summaryIds + ", createTime=" + createTime + ", mark=" + mark
				+ "]";
	}
    
    
    
}