package com.github.hzw.security.entity;

import java.util.Date;

public class OrderInput {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_input.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_input.cloth_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer clothId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_input.my_company_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String myCompanyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_input.salesman_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer salesmanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_input.status
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_input.create_time
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_input.id
     *
     * @return the value of order_input.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_input.id
     *
     * @param id the value for order_input.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_input.cloth_id
     *
     * @return the value of order_input.cloth_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getClothId() {
        return clothId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_input.cloth_id
     *
     * @param clothId the value for order_input.cloth_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setClothId(Integer clothId) {
        this.clothId = clothId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_input.my_company_code
     *
     * @return the value of order_input.my_company_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getMyCompanyCode() {
        return myCompanyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_input.my_company_code
     *
     * @param myCompanyCode the value for order_input.my_company_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setMyCompanyCode(String myCompanyCode) {
        this.myCompanyCode = myCompanyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_input.salesman_id
     *
     * @return the value of order_input.salesman_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getSalesmanId() {
        return salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_input.salesman_id
     *
     * @param salesmanId the value for order_input.salesman_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setSalesmanId(Integer salesmanId) {
        this.salesmanId = salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_input.status
     *
     * @return the value of order_input.status
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_input.status
     *
     * @param status the value for order_input.status
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_input.create_time
     *
     * @return the value of order_input.create_time
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_input.create_time
     *
     * @param createTime the value for order_input.create_time
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}