package com.github.hzw.security.entity;

import com.github.hzw.util.ExcelDataMapper;

public class ParamProperties {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_properties.id
     *
     * @mbggenerated Sun Mar 01 11:24:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_properties.demo
     *
     * @mbggenerated Sun Mar 01 11:24:19 CST 2015
     */
    private String demo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_properties.value
     *
     * @mbggenerated Sun Mar 01 11:24:19 CST 2015
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_properties.id
     *
     * @return the value of param_properties.id
     *
     * @mbggenerated Sun Mar 01 11:24:19 CST 2015
     */
    @ExcelDataMapper(title="id",order=1)
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_properties.id
     *
     * @param id the value for param_properties.id
     *
     * @mbggenerated Sun Mar 01 11:24:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_properties.demo
     *
     * @return the value of param_properties.demo
     *
     * @mbggenerated Sun Mar 01 11:24:19 CST 2015
     */
    public String getDemo() {
        return demo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_properties.demo
     *
     * @param demo the value for param_properties.demo
     *
     * @mbggenerated Sun Mar 01 11:24:19 CST 2015
     */
    public void setDemo(String demo) {
        this.demo = demo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_properties.value
     *
     * @return the value of param_properties.value
     *
     * @mbggenerated Sun Mar 01 11:24:19 CST 2015
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_properties.value
     *
     * @param value the value for param_properties.value
     *
     * @mbggenerated Sun Mar 01 11:24:19 CST 2015
     */
    public void setValue(String value) {
        this.value = value;
    }
}