package com.github.hzw.security.entity;

import java.util.Date;

public class ReturnGoodsProcess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_goods_process.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_goods_process.summary_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer summaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_goods_process.return_date
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Date returnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_goods_process.return_num
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer returnNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_goods_process.return_unit
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String returnUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_goods_process.statistics_num
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer statisticsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_goods_process.return_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String returnColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_goods_process.create_time
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_goods_process.mark
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_goods_process.id
     *
     * @return the value of return_goods_process.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_goods_process.id
     *
     * @param id the value for return_goods_process.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_goods_process.summary_id
     *
     * @return the value of return_goods_process.summary_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getSummaryId() {
        return summaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_goods_process.summary_id
     *
     * @param summaryId the value for return_goods_process.summary_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setSummaryId(Integer summaryId) {
        this.summaryId = summaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_goods_process.return_date
     *
     * @return the value of return_goods_process.return_date
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Date getReturnDate() {
        return returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_goods_process.return_date
     *
     * @param returnDate the value for return_goods_process.return_date
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_goods_process.return_num
     *
     * @return the value of return_goods_process.return_num
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getReturnNum() {
        return returnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_goods_process.return_num
     *
     * @param returnNum the value for return_goods_process.return_num
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setReturnNum(Integer returnNum) {
        this.returnNum = returnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_goods_process.return_unit
     *
     * @return the value of return_goods_process.return_unit
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getReturnUnit() {
        return returnUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_goods_process.return_unit
     *
     * @param returnUnit the value for return_goods_process.return_unit
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setReturnUnit(String returnUnit) {
        this.returnUnit = returnUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_goods_process.statistics_num
     *
     * @return the value of return_goods_process.statistics_num
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getStatisticsNum() {
        return statisticsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_goods_process.statistics_num
     *
     * @param statisticsNum the value for return_goods_process.statistics_num
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setStatisticsNum(Integer statisticsNum) {
        this.statisticsNum = statisticsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_goods_process.return_color
     *
     * @return the value of return_goods_process.return_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getReturnColor() {
        return returnColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_goods_process.return_color
     *
     * @param returnColor the value for return_goods_process.return_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setReturnColor(String returnColor) {
        this.returnColor = returnColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_goods_process.create_time
     *
     * @return the value of return_goods_process.create_time
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_goods_process.create_time
     *
     * @param createTime the value for return_goods_process.create_time
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_goods_process.mark
     *
     * @return the value of return_goods_process.mark
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_goods_process.mark
     *
     * @param mark the value for return_goods_process.mark
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setMark(String mark) {
        this.mark = mark;
    }
}