package com.github.hzw.security.entity;

public class SampleAdditional {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_additional.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_additional.sample_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private Integer sampleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_additional.factory_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String factoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_additional.factory_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String factoryColor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_additional.id
     *
     * @return the value of sample_additional.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_additional.id
     *
     * @param id the value for sample_additional.id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_additional.sample_id
     *
     * @return the value of sample_additional.sample_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public Integer getSampleId() {
        return sampleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_additional.sample_id
     *
     * @param sampleId the value for sample_additional.sample_id
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setSampleId(Integer sampleId) {
        this.sampleId = sampleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_additional.factory_code
     *
     * @return the value of sample_additional.factory_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getFactoryCode() {
        return factoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_additional.factory_code
     *
     * @param factoryCode the value for sample_additional.factory_code
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setFactoryCode(String factoryCode) {
        this.factoryCode = factoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_additional.factory_color
     *
     * @return the value of sample_additional.factory_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getFactoryColor() {
        return factoryColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_additional.factory_color
     *
     * @param factoryColor the value for sample_additional.factory_color
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setFactoryColor(String factoryColor) {
        this.factoryColor = factoryColor;
    }
}