package com.github.hzw.security.entity;

public class SampleInputWithBLOBs extends SampleInput {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_input.demand
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String demand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sample_input.mark
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_input.demand
     *
     * @return the value of sample_input.demand
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getDemand() {
        return demand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_input.demand
     *
     * @param demand the value for sample_input.demand
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setDemand(String demand) {
        this.demand = demand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sample_input.mark
     *
     * @return the value of sample_input.mark
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sample_input.mark
     *
     * @param mark the value for sample_input.mark
     *
     * @mbggenerated Sun Mar 01 06:50:08 CST 2015
     */
    public void setMark(String mark) {
        this.mark = mark;
    }
}