package com.github.hzw.security.entity;

import com.github.hzw.util.ExcelDataMapper;

public class TechnologyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology_info.id
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology_info.code
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private String pinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology_info.name
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column technology_info.mark
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology_info.id
     *
     * @return the value of technology_info.id
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    @ExcelDataMapper(title="id",order=1)
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology_info.id
     *
     * @param id the value for technology_info.id
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology_info.name
     *
     * @return the value of technology_info.name
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    @ExcelDataMapper(title="工艺名称",order=2)
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology_info.name
     *
     * @param name the value for technology_info.name
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column technology_info.mark
     *
     * @return the value of technology_info.mark
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    @ExcelDataMapper(title="备注",order=3)
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column technology_info.mark
     *
     * @param mark the value for technology_info.mark
     *
     * @mbggenerated Fri Feb 20 21:33:50 CST 2015
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

	public String getPinyin() {
		return pinyin;
	}

	public void setPinyin(String pinyin) {
		this.pinyin = pinyin;
	}

	@Override
	public String toString() {
		return "TechnologyInfo [id=" + id + ", pinyin=" + pinyin + ", name="
				+ name + ", mark=" + mark + "]";
	}
    
}